### ISSUE TITLE
Map domain

### ISSUE THREAD

**Issue by lukefretwell** [ATO-ASAP/website#3]
- [x] atoasap.org to ato-asap.github.io/website
- [ ] redirect atoasap.com to atoasap.org

**Comment by openprivacy** [comment]
These domains redirect to https://ato-asap.github.io/website/
- http://ato-asap.com
- http://ato-asap.org
- http://ato-asao.net

Notes:
1. Need to transfer ownership of these from Fen to CivicActions
2. Get www.* and HTTPS set up
3. There remains the atoasap.* (without the '-') domains to set up

**Comment by lukefretwell** [comment]
@openprivacy we actually have the atoasap.org and atoasap.com domain. I need to get with @grugnog to set it up. Or if you could coordinate, that would be even better.

**Comment by openprivacy** [comment]
Email sent to Henry asking to transfer atoasap.com to the civicactions account.

**Comment by lukefretwell** [comment]
@openprivacy I see it's redirecting from the .org but we should map the DNS to that.

**Comment by openprivacy** [comment]
DNS at Namecheap set up - see https://atoasap.org
